### ISSUE TITLE
PHP 8 not yet supported

### ISSUE THREAD

**Issue by powellblyth** [vyuldashev/laravel-openapi#26]
Hi there, 

it would be great if PHP 8 could be supported here please.

Is anyone working on it?

thanks

**Comment by gboquizosanchez** [comment]
It would be interesting... Sure

**Comment by vyuldashev** [comment]
Yes, there is a plan to get rid of Doctrine's Annotations and use PHP 8 Attributes.

**Comment by gboquizosanchez** [comment]
Awesome!

**Comment by billbarsch** [comment]
could you add php 8 to composer.json so i can install it in my projects?
it would be a temporary solution

**Comment by vyuldashev** [comment]
Guys, please take a look at PR #29 it includes support for PHP 8 and replaces Doctrine Annotations with PHP 8 Attributes. You are free to comment on it and I will release it on weekend.

**Comment by vyuldashev** [comment]
Package version v1.0.0 is released with PHP 8 support.

**Comment by genesiscz** [comment]
I understand you drop support for 7.x as there's no way it would work there, but was it necessary to drop the whole Annotations namespace? Wouldn't it be better to have a choice?
