### ISSUE TITLE
Website has error in example code

### ISSUE THREAD

**Issue by JoshPJackson** [vyuldashev/laravel-openapi#39]
In the first example code block here: https://vyuldashev.github.io/laravel-openapi/paths/operations.html#operations. The trait used is: 
`use Vyuldashev\LaravelOpenApi\Attributes as OpenApi;`

but should be 

`use Vyuldashev\LaravelOpenApi\Annotations as OpenApi;`

**Comment by sun-yryr** [comment]
Hello.

Before `v0.24.1` was using `Vyuldashev\LaravelOpenApi\Annotations`.
`v1.0.0` and later is using `Vyuldashev\LaravelOpenApi\Attributes`.

PHP8 is required to use v1.0.0 or later.
